### ISSUE TITLE
Unable to resolve module 'apollo-link-logger'

### ISSUE THREAD

**Issue by guilhermedecampo** [julliasaad/list-repos-app#1]
Hi! Could not run the app on expo client on iphone 5S. 

got `Failed building JavaScript bundle`
Check the image below:

![img_0816](https://user-images.githubusercontent.com/4806269/37930091-12882a1c-3118-11e8-85ec-3f1bf6447e91.PNG)

**Comment by julliasaad** [comment]
Fixed.
